import "./globals.css";
import Particle from "@/app/(components)/Particles";
import "react-toastify/dist/ReactToastify.css";
import {ToastContainer} from "react-toastify";
import React from "react";

export const metadata = {
    title: "Galaxy",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Particle/>
        <ToastContainer />
        {children}
        </body>
        </html>
    );
}
