import "./globals.css";
import Particle from "@/app/(components)/Particles";

export const metadata = {
    title: "Galaxy",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Particle/>
        {children}
        </body>
        </html>
    );
}
